context:
  name: polars-st
  version: "0.4.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/oreilles/polars-st/archive/refs/tags/${{ version }}.tar.gz
  sha256: 93211f1e19bb344f29a4b4304ed530ecb9d2ff24840ebb5d2ff693e301f93f52

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}

    - if: unix
      then: make
    - cargo-auditable
    - puccinialin
    - cargo-bundle-licenses
    - cmake
    - pip
  host:
    - maturin
    - python
    - pip
  run:
    - python
    - polars >1.34
    - pyogrio >0.9.0
    - pyarrow >=19.0.1
    - certifi

tests:
  - python:
      imports:
        - polars_st
      pip_check: true

about:
  homepage: https://github.com/oreilles/polars-st
  summary: 'Polars ST provides spatial operations on Polars DataFrames, Series, and Expressions.'
  description: |
    polars-st provides geometry operations under the namespace st on
    Polars Expr, Series, DataFrame and LazyFrame. Functions used to read
    files or parse geometries are available at the module root.
  license: LGPL-2.1-or-later
  license_file:
    - COPYING
    - THIRDPARTY.yml
  documentation: https://oreilles.github.io/polars-st/
  repository: https://github.com/oreilles/polars-st

extra:
  recipe-maintainers:
    - hobu
