conda_build_tool: rattler-build
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_forge_output_validation: true

azure:
  max_parallel: 25
bot:
  automerge: true

test: native_and_emulated
workflow_settings:
  free_disk_space: quick
  pagefile_size:
    - os: linux
      value: 15
    - os: win
      value: 16
  build_workspace_dir:
    - provider: azure
      os: win
      value: C:\\bld\\
provider:
  linux_aarch64: default
  osx_arm64: default
